name: GitHub Actions Web Shell

on:
  workflow_dispatch:

jobs:
  run-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ttyd & cloudflared
        run: |
          sudo apt-get update
          sudo apt-get install -y ttyd curl
          curl -L --output cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared

      - name: Start Web Shell & Cloudflare Tunnel
        run: |
          # Gunakan login -f runner untuk autologin otomatis tanpa password prompt
          ttyd -W -p 7681 login -f runner &
          echo "Starting Cloudflare Tunnel in background..."
          ./cloudflared tunnel --url http://localhost:7681 > tunnel.log 2>&1 &
          
          echo "Waiting for tunnel URL to generate..."
          sleep 6
          
          echo "=============================================="
          echo " CLOUDFLARE TUNNEL URL:"
          echo "=============================================="
          cat tunnel.log
          
          # Keep job alive
          wait
